version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/crazy-imagine-blog-strapi
    file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/install-dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start-server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop-server
      timeout: 300
      runas: root
